### ISSUE TITLE
Need to add "bundle install" command to Developer Setup

### ISSUE THREAD

**Issue by agilesix** [department-of-veterans-affairs/roadrunner-rails-starter-project#1]
I think developers will need to run "bundle install" between steps 3 and 4 in the Developer Setup instructions in order to get the starter kit running if they already have the bundler gem installed. Perhaps this step could be added to the ReadMe.

**Comment by shanear** [comment]
Yep, definitely needed to add that. Thanks @agilesix! 🙇
